"""
PDF theme generation utilities.

Used by ``md-doc theme init`` and ``md-doc theme override`` CLI commands,
and by the PDF builder when no _pdf-theme.css exists in the project tree.
"""

from __future__ import annotations

import os
from pathlib import Path
from string import Template


# ---------------------------------------------------------------------------
# Built-in defaults  (used when auto-generating on first build)
# ---------------------------------------------------------------------------

DEFAULTS = {
    "org_name":   "My Organisation",
    "primary":    "#1b4f72",
    "accent":     "#2e86c1",
    "body_text":  "#1a1a2e",
    "muted":      "#5d6d7e",
    "body_font":  "'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    "mono_font":  "'Consolas', 'Courier New', 'Liberation Mono', monospace",
    "page_size":  "A4",
}


def generate_default_theme() -> str:
    """Return a complete _pdf-theme.css using built-in defaults."""
    return generate_base_theme(**DEFAULTS)


# ---------------------------------------------------------------------------
# Color helpers
# ---------------------------------------------------------------------------

def _tint(hex_color: str, factor: float = 0.08) -> str:
    """
    Blend *hex_color* toward white.

    ``factor`` is the proportion of the original color (0 = white, 1 = original).
    factor=0.08 produces a very light background tint suitable for table stripes
    and code block backgrounds.
    """
    h = hex_color.lstrip("#")
    r = int(h[0:2], 16)
    g = int(h[2:4], 16)
    b = int(h[4:6], 16)
    r = round(r * factor + 255 * (1 - factor))
    g = round(g * factor + 255 * (1 - factor))
    b = round(b * factor + 255 * (1 - factor))
    return f"#{r:02x}{g:02x}{b:02x}"


def validate_hex_color(value: str) -> str:
    """Return the colour normalised to '#rrggbb', or raise ValueError."""
    v = value.strip()
    if not v.startswith("#"):
        v = "#" + v
    v = v.lower()
    if len(v) == 4:
        # Expand shorthand #abc → #aabbcc
        v = "#" + v[1] * 2 + v[2] * 2 + v[3] * 2
    if len(v) != 7 or not all(c in "0123456789abcdef" for c in v[1:]):
        raise ValueError(f"'{value}' is not a valid hex colour (expected #rrggbb)")
    return v


# ---------------------------------------------------------------------------
# CSS generation — base theme
# ---------------------------------------------------------------------------

_BASE_TEMPLATE = Template(r"""/* PDF Theme — $org_name
   Generated by md-doc theme init.
   Customise freely — this file is yours.
*/

/* ============================================
   PAGE SETUP
   ============================================ */
@page {
  size: $page_size;
  margin: 25mm 20mm 22mm 25mm;

  @bottom-left {
    content: "$org_name";
    font-size: 7.5pt;
    color: #7f8c9a;
    font-family: $body_font;
    border-top: 0.5pt solid #d5d8dc;
    padding-top: 3pt;
  }

  @bottom-center {
    content: string(research-date);
    font-size: 7.5pt;
    color: #7f8c9a;
    font-family: $body_font;
    border-top: 0.5pt solid #d5d8dc;
    padding-top: 3pt;
  }

  @bottom-right {
    content: "Page " counter(page) " of " counter(pages);
    font-size: 7.5pt;
    color: #7f8c9a;
    font-family: $body_font;
    border-top: 0.5pt solid #d5d8dc;
    padding-top: 3pt;
  }
}

@page cover {
  margin: 0;
  @bottom-left  { content: none; border: none; }
  @bottom-center { content: none; border: none; }
  @bottom-right { content: none; border: none; }
}

/* ============================================
   BASE
   ============================================ */
html, body {
  font-family: $body_font;
  font-size: 10.5pt;
  line-height: 1.65;
  color: $body_text;
  margin: 0;
  padding: 0;
  orphans: 3;
  widows: 3;
}

.running-date {
  string-set: research-date content();
  display: none;
}

/* ============================================
   COVER PAGE
   ============================================ */
.cover {
  page: cover;
  page-break-after: always;
  width: 210mm;
  height: 297mm;
  position: relative;
  background: white;
  overflow: hidden;
}

.cover-bar {
  background: $primary;
  height: 10mm;
  width: 100%;
}

.cover-stripe {
  position: absolute;
  top: 10mm;
  left: 0;
  width: 6mm;
  height: 120mm;
  background: $accent;
}

.cover-content {
  padding: 50mm 30mm 20mm 28mm;
}

.cover-label {
  font-size: 8.5pt;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 2.5pt;
  color: $accent;
  margin: 0 0 10mm 0;
}

.cover-title {
  font-size: 24pt;
  font-weight: 700;
  color: $primary;
  line-height: 1.2;
  margin: 0 0 8mm 0;
  border: none;
  padding: 0;
}

.cover-divider {
  border: none;
  border-top: 3pt solid $primary;
  width: 40mm;
  margin: 0 0 8mm 0;
}

.cover-meta {
  font-size: 10.5pt;
  color: $muted;
  margin: 0;
  line-height: 1.8;
}

.cover-meta strong {
  color: $body_text;
  font-weight: 600;
}

.cover-footer {
  position: absolute;
  bottom: 14mm;
  left: 28mm;
  right: 20mm;
  border-top: 1pt solid #d5d8dc;
  padding-top: 4mm;
  font-size: 8pt;
  color: #7f8c9a;
}

/* ============================================
   HEADINGS
   ============================================ */
h1 {
  font-size: 15pt;
  font-weight: 700;
  color: $primary;
  border-bottom: 1.5pt solid #d5d8dc;
  padding-bottom: 4pt;
  margin-top: 18pt;
  margin-bottom: 8pt;
  page-break-after: avoid;
  break-after: avoid;
}

h2 {
  font-size: 12.5pt;
  font-weight: 600;
  color: $accent;
  margin-top: 14pt;
  margin-bottom: 5pt;
  page-break-after: avoid;
  break-after: avoid;
}

h3 {
  font-size: 10.5pt;
  font-weight: 700;
  color: $muted;
  margin-top: 10pt;
  margin-bottom: 4pt;
  page-break-after: avoid;
  break-after: avoid;
}

h4 {
  font-size: 10pt;
  font-weight: 600;
  color: $body_text;
  margin-top: 8pt;
  margin-bottom: 2pt;
  page-break-after: avoid;
  break-after: avoid;
}

/* ============================================
   BODY TEXT
   ============================================ */
p { margin: 0 0 7pt 0; orphans: 3; widows: 3; }
ul, ol { padding-left: 16pt; margin: 3pt 0 8pt 0; }
li { margin-bottom: 3pt; line-height: 1.6; orphans: 2; widows: 2; }
li > p { margin: 2pt 0; }
strong { font-weight: 700; color: $primary; }
em { font-style: italic; color: $muted; }
a { color: $accent; text-decoration: none; }
a[href^="http"]::after { content: " <" attr(href) ">"; font-size: 7pt; color: #7f8c9a; word-break: break-all; }
a[href^="#"]::after, a:not([href^="http"])::after { content: ""; }

/* ============================================
   TABLES
   ============================================ */
table { border-collapse: collapse; width: 100%; margin: 6pt 0 12pt 0; font-size: 9.5pt; page-break-inside: avoid; }
thead { display: table-header-group; }
tr { page-break-inside: avoid; }
th { background: $primary; color: #ffffff; padding: 5pt 9pt; text-align: left; font-weight: 700; font-size: 8.5pt; letter-spacing: 0.4pt; text-transform: uppercase; }
td { padding: 5pt 9pt; border-bottom: 0.5pt solid #d5d8dc; vertical-align: top; }
tr:nth-child(even) td { background: $stripe_bg; }
tr:last-child td { border-bottom: 1pt solid #aab7c4; }

/* ============================================
   CODE
   ============================================ */
code { background: $code_bg; border-radius: 2pt; padding: 1pt 4pt; font-size: 8.5pt; color: $primary; font-family: $mono_font; }
pre { background: $pre_bg; border-left: 3pt solid $accent; border-radius: 3pt; padding: 8pt 10pt; font-size: 8pt; line-height: 1.5; margin: 6pt 0 10pt 0; page-break-inside: avoid; overflow: hidden; }
pre code { background: none; padding: 0; color: $body_text; font-size: 8pt; }

/* ============================================
   BLOCKQUOTE / CALLOUT
   ============================================ */
blockquote { border-left: 3pt solid $accent; margin: 6pt 0 8pt 0; padding: 4pt 10pt; color: $muted; font-style: italic; background: $pre_bg; page-break-inside: avoid; }
blockquote p { margin: 2pt 0; }
blockquote strong { color: $primary; }

/* ============================================
   MISC
   ============================================ */
hr { border: none; border-top: 1pt solid #d5d8dc; margin: 12pt 0; }
dl { margin: 6pt 0 10pt 0; }
dt { font-weight: 700; color: $primary; margin-top: 6pt; }
dd { margin-left: 14pt; margin-bottom: 4pt; color: $body_text; }
img { max-width: 100%; height: auto; display: block; margin: 8pt auto 12pt auto; page-break-inside: avoid; }
h1 + * { page-break-before: avoid; break-before: avoid; }
h2 + * { page-break-before: avoid; break-before: avoid; }
table, figure, blockquote, pre { page-break-inside: avoid; }
.appendix-template-break { page-break-before: always; break-before: page; height: 0; margin: 0; padding: 0; }
.report-body h1 { page-break-before: always; break-before: page; }

/* ============================================
   FORM FIELDS
   ============================================ */
form {
  display: block;
}

input[type="text"],
input[type="date"],
input[type="number"],
input[type="email"],
textarea,
select {
  appearance: auto;
  display: inline-block;
  width: 100%;
  padding: 4pt 6pt;
  margin: 2pt 0 8pt 0;
  border: 1pt solid $muted;
  border-radius: 2pt;
  font-family: $body_font;
  font-size: 10pt;
  color: $body_text;
  background: #fafafa;
}

input[type="checkbox"],
input[type="radio"] {
  appearance: auto;
  width: auto;
  margin-right: 4pt;
}

textarea {
  resize: vertical;
  min-height: 48pt;
}

input[type="submit"],
button[type="submit"] {
  appearance: auto;
  display: inline-block;
  padding: 6pt 18pt;
  background: $primary;
  color: white;
  border: none;
  border-radius: 2pt;
  font-size: 10pt;
  cursor: pointer;
}
""")


def generate_base_theme(
    org_name: str,
    primary: str,
    accent: str,
    body_text: str,
    muted: str,
    body_font: str,
    mono_font: str,
    page_size: str,
) -> str:
    """Return a fully populated _pdf-theme.css string."""
    return _BASE_TEMPLATE.substitute(
        org_name=org_name,
        primary=primary,
        accent=accent,
        body_text=body_text,
        muted=muted,
        body_font=body_font,
        mono_font=mono_font,
        page_size=page_size,
        stripe_bg=_tint(accent, 0.08),
        code_bg=_tint(accent, 0.06),
        pre_bg=_tint(accent, 0.08),
    )


# ---------------------------------------------------------------------------
# CSS generation — override theme
# ---------------------------------------------------------------------------

_OVERRIDE_TEMPLATE = Template(r"""/* PDF Theme override — $sub_name
   Inherits base layout and typography from the parent theme.
   Only brand colours and footer identity are redefined here.
*/
@import "$import_path";

@page {
  @bottom-left {
    content: "$sub_name";
    font-size: 7.5pt;
    color: #7f8c9a;
    border-top: 0.5pt solid #d5d8dc;
    padding-top: 3pt;
  }
}

/* Cover page */
.cover-bar    { background: $primary; }
.cover-stripe { background: $accent; }
.cover-label  { color: $accent; }
.cover-title  { color: $primary; }
.cover-divider { border-top-color: $primary; }

/* Headings and accents */
h1     { color: $primary; }
h2     { color: $accent; }
strong { color: $primary; }
a      { color: $accent; }

/* Tables and code */
th                    { background: $primary; }
tr:nth-child(even) td { background: $stripe_bg; }
code  { background: $code_bg; color: $primary; }
pre   { background: $pre_bg; border-left-color: $accent; }

/* Blockquotes */
blockquote        { border-left-color: $accent; background: $pre_bg; }
blockquote strong { color: $primary; }
dt { color: $primary; }
""")


def generate_override_theme(
    sub_name: str,
    import_path: str,
    primary: str,
    accent: str,
) -> str:
    """Return a minimal override _pdf-theme.css string."""
    return _OVERRIDE_TEMPLATE.substitute(
        sub_name=sub_name,
        import_path=import_path,
        primary=primary,
        accent=accent,
        stripe_bg=_tint(accent, 0.08),
        code_bg=_tint(accent, 0.06),
        pre_bg=_tint(accent, 0.08),
    )


# ---------------------------------------------------------------------------
# _meta.yml generation
# ---------------------------------------------------------------------------

def generate_meta_yml(org_name: str, cover_page: bool) -> str:
    cover_str = "true" if cover_page else "false"
    return f"""author: {org_name}
cover_page: {cover_str}
outputs: [pdf]
"""


# ---------------------------------------------------------------------------
# Parent theme discovery
# ---------------------------------------------------------------------------

def find_parent_theme(from_dir: Path) -> Path | None:
    """
    Walk up from *from_dir*'s parent looking for a _pdf-theme.css.
    Returns the first one found (nearest ancestor), or None.
    """
    current = from_dir.resolve().parent
    while True:
        candidate = current / "_pdf-theme.css"
        if candidate.exists():
            return candidate
        parent = current.parent
        if parent == current:
            return None
        current = parent


def relative_import_path(from_dir: Path, theme_path: Path) -> str:
    """Return the CSS @import path from *from_dir* to *theme_path*."""
    rel = os.path.relpath(theme_path, from_dir)
    return rel.replace(os.sep, "/")
