<?php

namespace MdDoc\FilamentMdDoc\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use MdDoc\FilamentMdDoc\Services\BuildRunner;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\Response;

class BuildController extends Controller
{
    public function __construct(protected BuildRunner $runner) {}

    /**
     * Serve a built PDF/DOCX referenced by a one-time build token.
     * The token is generated by BuildRunner::build() and cached for ~30 min.
     *
     * MIME types:
     *   pdf  → application/pdf  (rendered inline in <iframe>)
     *   docx → application/vnd.openxmlformats-officedocument.wordprocessingml.document
     *   dotx → application/vnd.openxmlformats-officedocument.wordprocessingml.template
     */
    public function serve(Request $request, string $token): Response
    {
        $entry = $this->runner->resolveToken($token);

        if ($entry === null) {
            abort(404, 'Build expired or token invalid');
        }

        $disposition = $entry['format'] === 'pdf' ? 'inline' : 'attachment';

        return (new BinaryFileResponse($entry['path']))
            ->setContentDisposition($disposition, $entry['filename']);
    }
}
